// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Entity {
    pub entity_id: u32,
    pub position: DbVector2,
    pub mass: u32,
}

impl __sdk::InModule for Entity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Entity`.
///
/// Provides typed access to columns for query building.
pub struct EntityCols {
    pub entity_id: __sdk::__query_builder::Col<Entity, u32>,
    pub position: __sdk::__query_builder::Col<Entity, DbVector2>,
    pub mass: __sdk::__query_builder::Col<Entity, u32>,
}

impl __sdk::__query_builder::HasCols for Entity {
    type Cols = EntityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            position: __sdk::__query_builder::Col::new(table_name, "position"),
            mass: __sdk::__query_builder::Col::new(table_name, "mass"),
        }
    }
}

/// Indexed column accessor struct for the table `Entity`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Entity, u32>,
}

impl __sdk::__query_builder::HasIxCols for Entity {
    type IxCols = EntityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Entity {}
