// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Food {
    pub entity_id: u32,
}

impl __sdk::InModule for Food {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Food`.
///
/// Provides typed access to columns for query building.
pub struct FoodCols {
    pub entity_id: __sdk::__query_builder::Col<Food, u32>,
}

impl __sdk::__query_builder::HasCols for Food {
    type Cols = FoodCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FoodCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Food`.
///
/// Provides typed access to indexed columns for query building.
pub struct FoodIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Food, u32>,
}

impl __sdk::__query_builder::HasIxCols for Food {
    type IxCols = FoodIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FoodIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Food {}
