// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpawnFoodTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for SpawnFoodTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpawnFoodTimer`.
///
/// Provides typed access to columns for query building.
pub struct SpawnFoodTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<SpawnFoodTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<SpawnFoodTimer, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for SpawnFoodTimer {
    type Cols = SpawnFoodTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpawnFoodTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SpawnFoodTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpawnFoodTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<SpawnFoodTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for SpawnFoodTimer {
    type IxCols = SpawnFoodTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpawnFoodTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpawnFoodTimer {}
