// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_2_type::DbVector2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerInputArgs {
    pub direction: DbVector2,
}

impl From<UpdatePlayerInputArgs> for super::Reducer {
    fn from(args: UpdatePlayerInputArgs) -> Self {
        Self::UpdatePlayerInput {
            direction: args.direction,
        }
    }
}

impl __sdk::InModule for UpdatePlayerInputArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_input {
    /// Request that the remote module invoke the reducer `update_player_input` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_player_input:update_player_input_then`] to run a callback after the reducer completes.
    fn update_player_input(&self, direction: DbVector2) -> __sdk::Result<()> {
        self.update_player_input_then(direction, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_player_input` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_player_input_then(
        &self,
        direction: DbVector2,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_player_input for super::RemoteReducers {
    fn update_player_input_then(
        &self,
        direction: DbVector2,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdatePlayerInputArgs { direction }, callback)
    }
}
