// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Entity
    {
        [DataMember(Name = "entity_id")]
        public uint EntityId;
        [DataMember(Name = "position")]
        public DbVector2 Position;
        [DataMember(Name = "mass")]
        public uint Mass;

        public Entity(
            uint EntityId,
            DbVector2 Position,
            uint Mass
        )
        {
            this.EntityId = EntityId;
            this.Position = Position;
            this.Mass = Mass;
        }

        public Entity()
        {
            this.Position = new();
        }
    }
}
