// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DebugHandler(ReducerEventContext ctx);
        public event DebugHandler? OnDebug;

        public void Debug()
        {
            conn.InternalCallReducer(new Reducer.Debug(), this.SetCallReducerFlags.DebugFlags);
        }

        public bool InvokeDebug(ReducerEventContext ctx, Reducer.Debug args)
        {
            if (OnDebug == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDebug(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Debug : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "debug";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DebugFlags;
        public void Debug(CallReducerFlags flags) => DebugFlags = flags;
    }
}
