[package]
name = "blackholio"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb-sdk = { version = "1.3.0" }
godot = { version = "0.3.4", features = ["__trace", "__debug-log"] }
tokio = { version = "1.47.1" }
lazy_static = "1.5"